package com.nutriscan.mpv.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

 public record Nutriments(
        Double carbohydrates,
        @JsonProperty("carbohydrates_100g") Double carbohydrates100g,
        @JsonProperty("carbohydrates_unit") String carbohydratesUnit,
        @JsonProperty("carbohydrates_value") Double carbohydratesValue,
        Double energy,
        @JsonProperty("energy-kcal") Double energyKcal,
        @JsonProperty("energy-kcal_100g") Double energyKcal100g,
        @JsonProperty("energy-kcal_unit") String energyKcalUnit,
        @JsonProperty("energy-kcal_value") Double energyKcalValue,
        @JsonProperty("energy-kcal_value_computed") Double energyKcalValueComputed,
        @JsonProperty("energy_100g") Double energy100g,
        @JsonProperty("energy_unit") String energyUnit,
        @JsonProperty("energy_value") Double energyValue,
        Double fat,
        @JsonProperty("fat_100g") Double fat100g,
        @JsonProperty("fat_unit") String fatUnit,
        @JsonProperty("fat_value") Double fatValue,
        @JsonProperty("fruits-vegetables-legumes-estimate-from-ingredients_100g") Double fruitsVegetablesLegumesEstimate100g,
        @JsonProperty("fruits-vegetables-legumes-estimate-from-ingredients_serving") Double fruitsVegetablesLegumesEstimateServing,
        @JsonProperty("fruits-vegetables-nuts-estimate-from-ingredients_100g") Double fruitsVegetablesNutsEstimate100g,
        @JsonProperty("fruits-vegetables-nuts-estimate-from-ingredients_serving") Double fruitsVegetablesNutsEstimateServing,
        @JsonProperty("nova-group") Integer novaGroup,
        @JsonProperty("nova-group_100g") Integer novaGroup100g,
        @JsonProperty("nova-group_serving") Integer novaGroupServing,
        @JsonProperty("nutrition-score-fr") Integer nutritionScoreFr,
        @JsonProperty("nutrition-score-fr_100g") Integer nutritionScoreFr100g,
        Double proteins,
        @JsonProperty("proteins_100g") Double proteins100g,
        @JsonProperty("proteins_unit") String proteinsUnit,
        @JsonProperty("proteins_value") Double proteinsValue,
        Double salt,
        @JsonProperty("salt_100g") Double salt100g,
        @JsonProperty("salt_unit") String saltUnit,
        @JsonProperty("salt_value") Double saltValue,
        @JsonProperty("saturated-fat") Double saturatedFat,
        @JsonProperty("saturated-fat_100g") Double saturatedFat100g,
        @JsonProperty("saturated-fat_unit") String saturatedFatUnit,
        @JsonProperty("saturated-fat_value") Double saturatedFatValue,
        Double sodium,
        @JsonProperty("sodium_100g") Double sodium100g,
        @JsonProperty("sodium_unit") String sodiumUnit,
        @JsonProperty("sodium_value") Double sodiumValue,
        Double sugars,
        @JsonProperty("sugars_100g") Double sugars100g,
        @JsonProperty("sugars_unit") String sugarsUnit,
        @JsonProperty("sugars_value") Double sugarsValue
) {}
